export const jobData = [
  {
    id: 0,
    title: 'Drilling And Well Engineering',
    subtitle: null,
    location: 'Remote / On Call',
    description: 'Our SMEs in drilling help clients reduce non-productive time, enhance rig performance, and optimize bit selection. Ideal for experts with field or office-based drilling experience.',
  },
  {
    id: 1,
    title: 'Well Integrity & Inspection',
    subtitle: null,
    location: 'Global',
    description: 'Support operators with major inspections, risk assessments, and regulatory compliance. Experience in CAT III/IV audits, API RP 90, and integrity management is a plus.',
  },
  {
    id: 2,
    title: 'Production & Artificial Lift',
    subtitle: 'Subject Matter Expert, ESP & Artificial Lift Systems',
    location: 'Remote',
    description: 'Provide clients with recommendations for optimizing artificial lift strategies and reducing system failures. Must have ESP/rod lift/jet pump design and troubleshooting experience.',
  },
  {
    id: 3,
    title: 'HSE & Regulatory Compliance',
    subtitle: 'SME, Health, Safety & Environmental (HSE)',
    location: 'Remote',
    description: 'Guide companies in building safety management systems, incident response, and training programs. Ideal for those with NEBOSH, OSHA, or ADNOC/Aramco compliance expertise.',
  },
  {
    id: 4,
    title: 'Energy Transition & Sustainability',
    subtitle: 'Consultant, Carbon Management & Sustainability',
    location: 'Remote',
    description: 'Help clients navigate carbon strategy, methane abatement, and flaring reduction plans. Suitable for experts in CCUS, ESG reporting, and oilfield sustainability programs.',
  },
  {
    id: 5,
    title: 'Digital Transformation & AI',
    subtitle: 'Advisor, Digital Oilfield & AI Applications',
    location: 'Global / Remote',
    description: 'Work with clients to digitize operations using AI, digital twins, and real-time monitoring. Seeking SMEs with experience in predictive maintenance, asset optimization, or SCADA.',
  },
  {
    id: 6,
    title: 'Reservoir & Petroleum Engineering',
    subtitle: 'Senior Consultant, Reservoir Simulation & Field Development',
    location: 'Middle East / Remote',
    description: 'Support with field development planning, material balance, or dynamic reservoir modeling. Proficiency in ECLIPSE, Petrel, or CMG preferred.',
  },
  {
    id: 7,
    title: 'Technical Expert, Cementing & Stimulation',
    subtitle: 'Senior Consultant, Reservoir Simulation & Field Development',
    location: 'MENATI / APAC',
    description: 'Assist in treatment design, post-job evaluation, and failure investigation. Experience in frac, acidizing, and zonal isolation strongly valued.',
  },
  {
    id: 8,
    title: 'Coordinator, SME Engagement & Sales Ops',
    subtitle: null,
    location: 'Dubai (Hybrid)',
    description: 'Help onboard SMEs, match them to client needs, and support consulting logistics. Great for someone with oilfield operations background and a flair for customer service.',
  },
];
